services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

  web:
    build: .
    volumes:
      - ./.env:/home/k24_c/mio/.c/.env
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/k24_c/mio/.homepage/c
        - action: rebuild
          path: pyproject.toml

volumes:
  mysql-data: